#!/bin/bash

file="${1}"

if [ -z "${file}" ]
then
    echo "Usage: md2pdf <file without extension>"
    exit 1
fi

if [ ! -f "${file}.md" ]
then
    echo "expected ${file}.md"
    exit 1
fi

pandoc -o "${file}.pdf" "${file}.md"

